export const RIDE_NAME_MAP: Record<string, string> = {
  "monimo-RUSH": "T 익스프레스 (모니모 러쉬)",
  "Amazon Express": "아마존 익스프레스",
  "Safari World :The Wild": "사파리 월드",
  "Lost Valley": "로스트 밸리",
  "Thunder Falls": "썬더 폴스",
  "Rolling X-Train": "롤링 엑스트레인",
  "Hurricane": "허리케인",
  "Double Rock Spin": "더블 락스핀",
  "Let’s Twist": "렛츠 트위스트",
  "Championship Rodeo": "챔피언쉽 로데오",
  "Columbus Adventure": "콜롬버스 어드벤처 (바이킹)",
  "Bumper Car": "범퍼카",
  "Panda World": "판다 월드",
  "Bao Haus": "바오 하우스",
  "Peter Pan": "피터팬",
  "Royal Jubilee Carousel": "로얄 쥬빌리 캐로셀 (회전목마)",
  "Flash Pang Pang": "플래쉬 팡팡",
  "Flying Elephant": "플라잉 엘리펀트",
  "Magic Cookie House": "매직 쿠키 하우스",
  "Lily Dance": "릴리 댄스",
  "Dragon Coaster": "드래곤 코스터",
  "Space Tour (4D Attraction)": "스페이스 투어 (4D)",

  "Sky Cruise(Top)": "스카이 크루즈 (상단)",
  "Sky Cruise(Bottom)": "스카이 크루즈 (하단)",
  "Sky Way(Top)": "스카이 웨이 (상단)",
  "Sky Way(Bottom)": "스카이 웨이 (하단)",
  "Human Sky(Top)": "휴먼 스카이 (상단)",
  "Human Sky(Bottom)": "휴먼 스카이 (하단)",

  "Adventure Carnival": "어드벤처 카니발",
  "Alpine Carnival": "알파인 카니발",
  "Ball House": "볼하우스",
  "Boong Boong Car": "붕붕카",
  "Festival train": "페스티발 트레인",
  "Flying Rescue": "플라잉 레스큐",
  "Fortune Market": "포춘 마켓",
  "Game Adventure": "게임 어드벤처",
  "Game Pia": "게임피아",
  "Jubilee Games": "쥬빌리 게임즈",
  "Kingdom of Cars": "자동차 왕국",
  "Lenny's Magic School": "레니의 마법학교",
  "Magic Swing": "매직 스윙",
  "MEMORY CARNIVAL": "메모리 카니발",
  "Panda 2nd House": "판다 하우스 2호점",
  "Play Yard": "플레이 야드",
  "Racing Coaster": "레이싱 코스터",
  "Rail Slide": "레일 슬라이드",
  "Robot Car": "로봇카",
  "Shooting Ghost": "슈팅 고스트",
  "Sky Dancing": "스카이 댄싱",
  "Spooky Fun House": "스푸키 펀 하우스",
  "Top Jet": "탑 제트"
};

export function getKoName(enName: string): string {
  return RIDE_NAME_MAP[enName] || enName;
}